'use strict';
// Approved onboarding, savings, rewards and WageScore components from round two.
const goalCard=(s,name,amt,target,ic,action='deposit')=>`<div class="goal-card"><div class="row"><span class="goal-icon">${icon(ic)}</span><h4>${name}</h4>${btn(icon('Plus'),action,'icon-button',`aria-label="Add money to ${name}" data-goal="${name}"`)}</div><div class="row"><strong>${naira(amt)}</strong><span class="tiny text-muted">of ${naira(target)}</span></div><div class="progress" role="img" aria-label="${Math.round(amt/target*100)} percent of ${name} goal"><i style="width:${Math.min(100,amt/target*100)}%"></i></div><div class="row"><span class="tiny text-muted">${Math.round(amt/target*100)}% of your goal</span><span class="tiny">Little by little ↗</span></div></div>`;

function cashArt(){return `<svg viewBox="0 0 320 270" role="img" aria-label="An illustrated salary card, naira coins and sparkles"><g stroke="#0F172A" stroke-width="2" stroke-linejoin="round"><g transform="rotate(-14 159 139)"><rect x="60" y="57" width="204" height="137" rx="16" fill="#0F172A"/><rect x="53" y="50" width="204" height="137" rx="16" fill="#C084FC"/><path d="M63 76q29-35 59 0t59 0t65 0" fill="none" stroke="#F3E8FF" stroke-width="17"/><path d="M141 86l-29 40h27l-11 32 47-49h-29l9-23" fill="#F3E8FF" stroke="none"/><text x="72" y="167" fill="#0F172A" stroke="none" font-family="DM Sans" font-size="16" font-weight="700">YOUR EARNED PAY</text><rect x="203" y="106" width="30" height="23" rx="5" fill="#F3E8FF"/><path d="M218 107v22M203 115h30M211 116v13" fill="none"/></g><g transform="translate(35 7) rotate(-15 38 45)"><ellipse cx="47" cy="48" rx="31" ry="37" fill="#9D4EDD"/><ellipse cx="39" cy="46" rx="31" ry="37" fill="#fff"/><text x="19" y="61" font-family="Manrope" font-size="42" stroke="none" font-weight="800">₦</text></g><g transform="translate(221 160) rotate(17 30 30)"><ellipse cx="39" cy="35" rx="31" ry="37" fill="#9D4EDD"/><ellipse cx="31" cy="33" rx="31" ry="37" fill="#F3E8FF"/><text x="11" y="48" font-family="Manrope" font-size="42" stroke="none" font-weight="800">₦</text></g><g transform="translate(32 187) rotate(12 23 23)"><rect x="5" y="5" width="45" height="45" rx="10" fill="#0F172A"/><rect width="45" height="45" rx="10" fill="#9D4EDD"/><path d="M23 7q0 16 16 16q-16 0-16 16q0-16-16-16q16 0 16-16" fill="#F3E8FF" stroke="none"/></g><path d="M275 23v27m-13-13h26M291 90l9 4-9 4-4 10-4-10-9-4 9-4 4-9z" fill="#C084FC"/><path d="M18 119q-17 16 0 31t0 26" stroke="#9D4EDD" fill="none" stroke-width="3"/><path d="M97 235q36 12 72-2" stroke="#9D4EDD" fill="none" stroke-width="2"/></g></svg>`;}

function welcome(s){return `<div class="screen-pad welcome"><header class="app-header">${appLogo()}<span class="badge">Made for you</span></header><div class="welcome-art">${cashArt()}</div><div><h1 class="app-h1">Life doesn’t wait.<br>Why should<br>your salary?</h1><p class="welcome-desc">Access the pay you’ve earned.<br>Make room for the things that matter.</p></div><div class="onboarding-dots" aria-label="Introduction"><i class="active"></i><i></i><i></i></div><div class="onboarding-actions">${go(`Get started ${icon('ArrowUpRight')}`,'priorities')}${go('Explore the demo','home','button-secondary')}</div></div>`;}

function priorities(s){return `<div class="screen-pad">${header('A little about you',s,'welcome')}<span class="badge">01 / YOUR PRIORITIES</span><h1 class="app-h1">Let’s start<br>with what matters.</h1><p class="small text-muted">Your money, your plans. What brings you here?</p><div class="stack">${[['salary','Zap','A little before payday','Access the pay you’ve earned.'],['saving','PiggyBank','Something for tomorrow','Build a savings habit, your way.'],['wellness','TrendingUp','A clearer money picture','Understand your financial progress.']].map(([id,ic,title,sub])=>btn(`${icon(ic)}<div><strong>${title}</strong><small>${sub}</small></div><span class="select-ring">${s.priority===id?icon('Check'):''}</span>`,'priority','priority-card',`data-value="${id}" aria-pressed="${s.priority===id}"`)).join('')}</div><p class="tiny text-muted">You can explore all of Wagezapp, whichever you choose.</p><div class="grow"></div>${btn(`Continue ${icon('ArrowRight')}`,'priority-next','button-primary',s.priority?'':'disabled')}${go('I’ll explore first','home','button-link')}</div>`;}

function shieldArt(){return `<svg class="shield-art" viewBox="0 0 170 180" role="img" aria-label="A shield protecting your identity"><path d="M27 40Q84 2 141 40v57q0 48-57 75q-57-27-57-75Z" fill="#9D4EDD"/><path d="M35 32Q92-6 149 32v57q0 48-57 75q-57-27-57-75Z" fill="#F3E8FF" stroke="#0F172A" stroke-width="3"/><path d="M49 44q43-26 86 0v46q0 33-43 58q-43-25-43-58Z" fill="none" stroke="#0F172A" stroke-width="3"/><path d="m70 87 17 17 30-42" fill="none" stroke="#0F172A" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><g stroke="#0F172A" stroke-width="3" stroke-linecap="round"><path d="m4 66 13 4M2 86h13m-9 21 12-5M158 69l10-4m-11 23h10m-11 15 10 5"/></g></svg>`;}

function verify(s){return `<div class="screen-pad verify-screen">${header('Safe from the start',s,'priorities')}${shieldArt()}<h1 class="app-h1">Your identity.<br>In safe hands.</h1><p class="small text-muted">A few checks help protect your account and connect your salary to you.</p><div class="verification-steps">${[['1','Confirm your BVN','Match your bank identity.'],['2','Add your NIN','Confirm your identity details.'],['3','Take a quick selfie','Make sure it’s really you.']].map(([n,t,b])=>`<div class="verification-step"><b>${n}</b><div>${t}<small>${b}</small></div></div>`).join('')}</div><div class="grow"></div><p class="tiny text-muted">This preview uses a sample account. You won’t be asked for personal documents.</p>${go(`Continue to demo ${icon('ArrowRight')}`,'home')}${info('Why do we ask for this?','Your identity checks','BVN, NIN and a liveness check help match an account to its owner. The full product must show its privacy notice and consent before collecting information. This demo collects none.','button-link')}</div>`;}

function savings(s){return `<div class="screen-pad savings-screen">${header('Your savings',s)}<section class="savings-hero"><div class="row"><span class="small">A little more peace of mind</span>${icon('PiggyBank')}</div>${money(s.savings)}<p class="tiny">Saved towards your next chapter</p><span class="coin-mini" aria-hidden="true">₦</span></section><div class="mini-grid">${btn(`${icon('Plus')} Add money`,'deposit','button-primary')}${info('Withdraw','Savings withdrawal','In the full app, you can move available savings back to your verified bank account. This direction focuses on adding to a goal; no withdrawal is made here.','button-secondary')}</div><div><div class="section-top"><h3>Your goals</h3>${btn('New goal +','new-goal','text-button')}</div><div class="stack">${goalCard(s,'Rainy day fund',s.emergency,100000,'ShieldCheck')}${goalCard(s,'A place of my own',s.rent,80000,'Home','rent-deposit')}${s.newGoal?goalCard(s,escapeText(s.newGoal),s.newGoalAmount,50000,'Target','new-deposit'):''}</div></div><div class="callout">${icon('RefreshCw')}<div><strong>Let payday do the saving</strong><p>${s.autoSave?'₦5,000 set aside each payday.':'Automatic saving is paused.'}</p></div>${btn(icon('Settings2'),'autosave','icon-button','aria-label="Manage automatic saving"')}</div></div>`;}

function rewards(s){return `<div class="screen-pad rewards-screen">${header('Little wins',s)}<div><h1 class="app-h2">Good habits.<br>A little thank you.</h1><p class="small text-muted" style="margin-top:8px">Your rewards, all in one place.</p></div><section class="reward-hero"><h3>YOUR MONTHLY<br>GOOD THING.</h3><p>A partner voucher to brighten your everyday.</p><span class="badge">${icon('Ticket')} September reward</span>${icon('Ticket')}</section>${btn(s.claimed?'View demo voucher':'Preview your voucher','voucher','button-primary')}<div class="reward-grid">${[['PiggyBank','Savings starter','Your first goal is underway.',true],['CalendarDays','Steady steps','Keep your payday plan.',false],['ShieldCheck','Account verified','You’re all set to get going.',false],['TrendingUp','Progress, recognised','Explore your WageScore.',true]].map(([ic,title,sub,hi])=>info(`<span class="reward-medal">${icon(ic)}</span><strong>${title}</strong><small>${sub}</small>`,title,`${sub} Milestones in this demo are illustrative. Voucher partners, reward values and eligibility will be confirmed before launch.`,`reward-tile ${hi?'featured':''}`)).join('')}</div><p class="tiny text-muted">Sample rewards shown for design review. Partner offers may vary.</p></div>`;}

function score(s){return `<div class="screen-pad score-screen">${header('Your WageScore',s)}<div><h1 class="app-h2">Steady looks<br>good on you.</h1><p class="small text-muted" style="margin-top:9px">A view of your financial progress.</p></div><div class="score-orbit"><svg viewBox="0 0 240 240" aria-hidden="true"><circle cx="120" cy="120" r="103" fill="none" stroke="#E5E7EB" stroke-width="10"/><circle cx="120" cy="120" r="103" fill="none" stroke="#9D4EDD" stroke-width="10" stroke-linecap="round" stroke-dasharray="419 647"/></svg><div class="score-value"><strong>688</strong><small>out of 900 · Steady</small></div></div><div class="row"><span class="badge">${icon('TrendingUp')} +24 points this month</span><span class="tiny text-muted">Range 300 to 900</span></div><div><div class="section-top"><h3>What’s helping</h3></div>${[['CheckCheck','On-time repayments','Your recent repayments are up to date.'],['PiggyBank','A growing savings habit','You’re making space for tomorrow.'],['BriefcaseBusiness','Verified employment','Your employer is connected.']].map(([ic,t,b])=>info(`<span class="transaction-icon">${icon(ic)}</span><span class="transaction-info"><strong>${t}</strong><small>${b}</small></span>${icon('ChevronRight')}`,t,b,'transaction')).join('')}</div><p class="tiny text-muted">An illustrative Wagezapp score. Final scoring and eligibility rules are subject to confirmation.</p></div>`;}

function keypad(kind){return `<div class="keypad" aria-label="${kind==='pin'?'Transaction PIN':'Amount'} keypad">${['1','2','3','4','5','6','7','8','9',kind==='pin'?'clear':'00','0','delete'].map(k=>btn(k==='delete'?icon('Delete'):k==='clear'?'C':k,kind==='pin'?'pin-key':'amount-key','',`data-value="${k}" aria-label="${k==='delete'?'Delete last digit':k==='clear'?'Clear PIN':k}"`)).join('')}</div>`;}

function review(s){return `<div class="screen-pad">${header('Review your advance',s,'advance')}<div class="review-amount"><p>You’ll receive</p>${money(s.amount)}</div><div class="review-list"><div class="row"><span>To your account</span><strong>Salary account · 4821</strong></div><div class="row"><span>Advance fee</span><strong>₦0.00</strong></div><div class="row"><span>Total repayment</span><strong>${naira(s.amount)}</strong></div><div class="row"><span>Repayment date</span><strong>30 September</strong></div><div class="row"><span>Repayment method</span><strong>Payroll deduction</strong></div><div class="row"><span>Still available after this</span><strong>${naira(remaining(s)-s.amount)}</strong></div></div><label class="consent"><input type="checkbox" data-consent ${s.consent?'checked':''}><span>I understand that ${naira(s.amount)} will be deducted from my salary on 30 September.</span></label><div class="grow"></div>${btn('Continue to confirmation','confirm-review','button-primary',s.consent?'':'disabled')}<p class="privacy-note">${icon('ShieldCheck')} Employer partnered · No advance fee</p></div>`;}

function pin(s){return `<div class="screen-pad pin-screen">${header('Confirm it’s you',s,'review')}${icon('LockKeyhole')}<h1 class="app-h2">One last check.</h1><p class="small text-muted">Enter your 4 digit transaction PIN<br>to confirm ${naira(s.amount)}.</p><div class="pin-dots" aria-label="${s.pin.length} of 4 digits entered">${[0,1,2,3].map(n=>`<i class="pin-dot ${s.pin.length>n?'filled':''}"></i>`).join('')}</div><p class="badge" style="align-self:center">Demo PIN: 1234</p>${s.pinError?`<p class="field-error" role="alert">Use 1234 for this sample account.</p>`:''}<div class="grow"></div>${keypad('pin')}${btn('Confirm demo advance','complete','button-primary',s.pin.length===4?'':'disabled')}<p class="privacy-note">This only updates the sample account.</p></div>`;}

function success(s){return `<div class="screen-pad success-screen">${header('Your advance',s)}<div class="success-emblem">${icon('CheckCheck')}</div><h1 class="success-title">A little breathing room.</h1><p class="success-copy">${naira(s.amount)} has been added to your sample salary account. You’re all set.</p><div class="review-list"><div class="row"><span>Amount received</span><strong>${naira(s.amount)}</strong></div><div class="row"><span>Advance fee</span><strong>₦0.00</strong></div><div class="row"><span>Repayment</span><strong>30 September</strong></div><div class="row"><span>Reference</span><strong>WZ-DEMO-4821</strong></div></div><div class="grow"></div>${btn(`${icon('Download')} Save demo receipt`,'receipt','button-secondary')}${go('Back to home','home')}<p class="privacy-note">Demo complete. No real money was transferred.</p></div>`;}
